dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: KnMjUInpXtu8wW97z1z5JlvzqYRU2nMX3TucJYYcITK/koF4DM4fFY6pTZFa7vAJ+hkui9MPR5DG2YnJAoWdVyuNLbVezHVcvMyr/TMnEvPo2QTMFXFFvsObg2DOfrp5ewFyoPgVeWSU1HGEUYjsV4yUY7ujLgYLDIu7XtyWQBIwJezrS4Q1axfJLQu05K+5/VDt2xuXK2sd4svE3KHMegrRe/gZ3P0Fkmjg3kYBYPvxX+JEAxIBwoBgKU1hStAR0nZTb8GHhLPVG0KoRu5WqbWw3GbqxoBg5sb6HCPhGTHtm5cFk+5jo9u0aD+5bH04IxYezKnfQGdXPXv9UM6bxWswuvAcSaNjhcnpV/X+JGugZxmdrqGCc9OyVSItKBQ6hkEAPH+Wba5jWVRUq8g33EiXzWjJg8JWX/tkNjB6C9z+pib21eITrxcv5qdaEvCdJYxV53Lnye/8z+goyBurImcJO8Gdcu8oaX5qR4yYFzsR1kf9ze2JeReRKC/+I705Q6+Zqpg84DD9AXPPfSu+aqvmZCPsQEsHF9vum7M10ElfRXHxoOCCPe9HTGWkP8O6Y1roAH/BWF+JFWZBMO80FECUc26SPxQoXBCwphSCzHyLG8JbiLIlZ60yWLmmo/D8V4w98gDBk5j+Yb/M2cCFGyHtonDK2tI5otRaGJh8ncc=
  file: Gerbers/PRO-100_gerbers.zip
  on:
    repo: w4xzr/PRO-100
  skip_cleanup: 'true'
